[2023-09-13 22:39:50,058] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.0.148:5000 (Press CTRL+C to quit) - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:38,694] WARNING get_login() L134  Erro ao buscar usuário 'gladis@gmail.com', Registro de usuario não encontrado na base :/ - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\app.py L134 
[2023-09-13 22:40:38,697] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:38] "[33mPOST /login HTTP/1.1[0m" 404 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:51,028] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:51] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:51,254] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:51] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:52,306] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:52] "GET /openapi/static/images/swagger.svg HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:52,353] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:52] "GET /openapi/static/images/redoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:52,362] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:52] "GET /openapi/static/images/rapidoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:57,441] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:57] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:57,542] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:57] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:57,628] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:57] "GET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:57,849] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:57] "GET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:40:58,378] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:40:58] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:41:38,773] ERROR log_exception() L1449 Exception on /usuario [POST] - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'add_usuario' did not return a valid response. The function either returned None or ended without a return statement.
[2023-09-13 22:41:38,782] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:41:38] "[35m[1mPOST /usuario HTTP/1.1[0m" 500 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:42:09,116] ERROR log_exception() L1449 Exception on /usuario [POST] - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'add_usuario' did not return a valid response. The function either returned None or ended without a return statement.
[2023-09-13 22:42:09,121] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:42:09] "[35m[1mPOST /usuario HTTP/1.1[0m" 500 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:42:18,102] ERROR log_exception() L1449 Exception on /usuario [POST] - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\flask\app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'add_usuario' did not return a valid response. The function either returned None or ended without a return statement.
[2023-09-13 22:42:18,113] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:42:18] "[35m[1mPOST /usuario HTTP/1.1[0m" 500 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:42:30,244] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:42:30] "PUT /usuario HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-13 22:42:38,159] INFO _log() L224  10.0.0.148 - - [13/Sep/2023 22:42:38] "DELETE /usuario HTTP/1.1" 200 - - call_trace=C:\Users\Robson\OneDrive\Documentos\PUC\SPRINT 3\Backend\MVP-PUCRJ-Modulo-3-backend\MVP-PUCRJ-Modulo-3-backend\meu_app_api\venv\lib\site-packages\werkzeug\_internal.py L224 
